name = "cf-workers-telegram-bot"
main = "dist/worker.mjs"

account_id = "25b4eaa2743ee4936a9421aff173594d"
workers_dev = true
compatibility_date = "2022-02-16"

build.command = "npm install && npm run build"
